# -*- coding: utf-8 -*-
"""Módulo 2 - Aula 1 - Parte 2 - bibiliotecas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Py7gtsbDKDlsQWQeDtockWBGgk12hr5E
"""

################################################## BIBLIOTECA NUNPY ##################################################

import numpy as np

#array = np.array([1,2,3,40,15,92,20])
#
#print(array * 3)
#print(array ** 2)
#print(array.mean())


# [valor da compra, quantidade, desconto]
array2 = np.array([[100, 2, 15],[120, 3, 10],[269, 1, 0],[300, 5, 25]])
print(array2)

soma_coluna = np.sum(array2, axis=0)

print(soma_coluna)

soma_linha = np.sum(array2, axis=1)
print(soma_linha)

################################################## BIBLIOTECA PANDAS ##################################################
import pandas as pd

dados = {
    'Nome' : ['Ana', 'Bruno', 'Carlos'],
    'Idade' : [25, 30, 35],
    'Cidade': ['Rio de Janeiro', 'São Paulo', 'Belo Horizonte']
}

df = pd.DataFrame(dados)

#print(df)

nomes = df['Nome']

#print(nomes)

maior_de_30 = df[df["Idade"] >= 30]
#print("Pessoas com mais de 30 anos: \n", maior_de_30)

df["Salário"] = [5000, 2300, 3400]
print(df)

media_idade = df["Idade"].mean()
print("Média de Idade", media_idade)

################################################## BIBLIOTECA PANDAS ##################################################
import pandas as pd

def verifica_valor(valor):
    if valor > 50:
        return "Maior que 50"
    else:
        return "Menor ou Igual a 50"

# Carregando o arquivo CSV no DataFrame
df = pd.read_csv("https://drive.google.com/uc?id=1TVkLLP5a68yj9ee2c5SDzDxgRGUrXqx-", sep=";")

#print(df.head())
#print(df.info())
#print(df.describe())
print(df)

#nomes_categorias = df['Categoria']
#print(nomes_categorias)

#maior_de_30 = df[df["Idade"] >= 30]
#print("Pessoas com mais de 30 anos: \n", maior_de_30)

#df["Faixa de Valor"] = df['Valor Compra'].apply(verifica_valor)
#print(df)

#media_por_categoria = df.groupby('Categoria')['Valor Compra'].mean()
#print(media_por_categoria)

import matplotlib.pyplot as plt

meses = [ 'Jan', 'Fev', "Março", 'Abril', 'Maio', 'Junho']
vendas= [220, 330, 150, 120, 680, 20]

#plt.plot(meses, vendas)

plt.bar(meses, vendas)

plt.title("Vendas mensais primeiro semestre")
plt.xlabel("Meses")
plt.ylabel("Venda")

plt.show()

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt


dados = {
    'Marketing' : [50, 60, 70, 60, 75, 80],
    'Vendas' : [200, 220, 250, 275, 300, 320]
}

df = pd.DataFrame(dados)

sns.scatterplot(x='Marketing', y='Vendas', data=df)

plt.title('Relação de investimento em Marketing e Vendas')

plt.show()